name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Hugging Face Docker Registry
        uses: docker/login-action@v2
        with:
          registry: hf.co
          username: ${{ github.actor }}
          password: ${{ secrets.HF_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: registry.hf.space/bharatnilam/trackr-api:latest # Replace with your details
          secrets: |
            "APP_KEY=${{ secrets.APP_KEY }}"

      - name: Trigger Space restart
        uses: huggingface/restart-space-action@v1
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          space: bharatnilam/trackr-api # Replace with your details